export const fontawesome = {
  icons: {
    brands: [
      'faFacebookF',
      'faInstagram',
      'faTwitter',
    ],
  },
  proIcons: {
    light: [
      'faAngleDown',
      'faAngleRight',
      'faAngleUp',
      'faArrowUpRightFromSquare',
      'faBars',
      'faCheck',
      'faEnvelope',
      'faMinus',
      'faPlus',
      'faXmark',
    ],
    duotone: [
      'faArrowsRepeat',
      'faBasketShopping',
      'faCalendarDay',
      'faCalendarDays',
      'faChild',
      'faCircleInfo',
      'faCreditCardFront',
      'faEnvelope',
      'faFutbol',
      'faImageSlash',
      'faLocationDot',
      'faPhone',
      'faShirt',
      'faSignature',
      'faTicket',
      'faUsers',
      'faUsersBetweenLines',
      'faVenusMars',
    ],
  },
}
